### ISSUE TITLE
error at installing via adb

### ISSUE THREAD

**Issue by kurokirasama** [joaomgcd/TaskerSettings#34]
I tried installing the apk as suggested in your github page,

```bash
adb install --bypass-low-target-sdk-block Tasker.Settings.1.7.1.Huawei.Xiaomi.apk.apk
```
but I got this error message:
```bash
adb: failed to install Tasker.Settings.1.7.1.Huawei.Xiaomi.apk.apk: 
Exception occurred while executing 'install':
java.lang.IllegalArgumentException: Unknown option --bypass-low-target-sdk-block
    at com.android.server.pm.PackageManagerShellCommand.makeInstallParams(PackageManagerShellCommand.java:3213)
    at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:1427)
    at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:221)
    at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
    at android.os.ShellCommand.exec(ShellCommand.java:38)
    at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onShellCommand(PackageManagerService.java:6267)
    at android.os.Binder.shellCommand(Binder.java:1054)
    at android.os.Binder.onTransact(Binder.java:882)
    at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4313)
    at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:6251)
    at android.os.Binder.execTransactInternal(Binder.java:1290)
    at android.os.Binder.execTransact(Binder.java:1249
```
Do you know any workaround?

I'm on a Xiaomi Note 12 5G pro under MIUI 14. And I'm trying adb from Ubuntu 20.04.

Regards,

**Comment by joaomgcd** [comment]
You don't need to use ADB to install on that device. You can simply download the APK on the phone and install it directly.
