### ISSUE TITLE
adb install problem

### ISSUE THREAD

**Issue by etofi** [joaomgcd/TaskerSettings#37]
I can't install the app via adb.

```
C:\Program Files (x86)\Minimal ADB and Fastboot>adb install --bypass-low-target-sdk-block Tasker.Settings.1.6.0.apk
Performing Streamed Install
adb: failed to install Tasker.Settings.1.6.0.apk:
Exception occurred while executing 'install':
java.lang.IllegalArgumentException: Unknown option --bypass-low-target-sdk-block
        at com.android.server.pm.PackageManagerShellCommand.makeInstallParams(PackageManagerShellCommand.java:3242)
        at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:1429)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:230)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCo
```

**Comment by joaomgcd** [comment]
Hi. Please remove the --bypass-low-target-sdk-block part. Thanks
